name:               enum-text
version:            0.5.2.1
github:             "cdornan/enum-text"
license:            BSD3
author:             "Chris Dornan"
maintainer:         "chris@chrisdornan.com"
copyright:          "2019 Chris Dornan"
category:           Text
synopsis:           "A text rendering and parsing toolkit for enumerated types"

extra-source-files:
- README.md
- ChangeLog.md

description:        A text rendering and parsing toolkit for enumerated types.
                    Please see the README on GitHub at <https://github.com/cdornan/enum-text#readme>

dependencies:
- base >= 4.9 && < 10
- array
- attoparsec
- bytestring
- fmt
- hashable
- possibly
- scientific
- text
- time
- unordered-containers

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  enum-text-tests:
    main:                Doctest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - doctest-discover
    - enum-text
